version: 0.0
os: linux
files:
  - source: /build
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root

