version: 0.2

phases:
    install:
        commands:
            - echo "Installing dependencies..."
            - npm ci

    build:
        commands:
            - echo "Building the React app..."
            - npm run build
            - mkdir -p out
            - cp appspec.yml out/
            - cp -r dist/ out/

post_build:
    commands:
        - echo "Setting permissions for files..."
        - chmod -R 755 build/ # Ensure the build folder has read and execute permissions
        - chmod -R 755 scripts/ # Make scripts executable
        - mkdir -p out

        # Copy necessary files to 'out' directory
        - cp appspec.yml out/ || echo "appspec.yml not found"
        - cp -r build/ out/ || echo "Build folder not found"
        - cp -r scripts/ out/ || echo "Scripts folder not found"
        - cd out
        - zip -r ../deployment-package.zip .

artifacts:
    files:
        - appspec.yml
        - dist/**
        - deployment-package.zip
