version: 0.2

phases:
    install:
        commands:
            - echo "Installing dependencies..."
            - npm ci

    build:
        commands:
            - echo "Building the React app..."
            - npm run build
            - mkdir -p out
            - cp appspec.yml out/
            - cp -r dist/ out/

post_build:
    commands:
      - echo "Setting permissions for files..."
      - chmod -R 755 dist/  # Ensure 'dist/' is readable
      - chmod -R 755 scripts/  # Make scripts executable

      - echo "Packaging files into deployment-package.zip..."
      - mkdir -p out
      - cp appspec.yml out/
      - cp -r dist/ out/
      - cp -r scripts/ out/
      - cd out
      - zip -r ../deployment-package.zip .
      - echo "Deployment package created."

artifacts:
    files:
        - appspec.yml
        - dist/**
        - deployment-package.zip
    discard-paths: yes

